# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: 'install'
  
- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: AzureFileCopy@4
  displayName: 'Deploy to Blob Storage'
  inputs:
    SourcePath: './build'
    azureSubscription: 'dam.net.br'
    Destination: 'AzureBlob'
    storage: 'mercuriofront'
    ContainerName: '$web'
