# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- master

stages:
  - stage: sBuild
    displayName: Build & Pack
    jobs:
      - job: jBuild
        displayName:  Build & Pack
        pool:
          vmImage: 'ubuntu-latest'
        workspace:
          clean: all
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '14.x'

          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              command: 'install'
            
          - task: Npm@1
            displayName: 'Build'
            inputs:
              command: 'custom'
              customCommand: 'run build'
          
          - task: PublishBuildArtifacts@1
            displayName: Publish statics
            inputs:
              PathtoPublish: './build'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: sDeploy
    displayName: Deploy to Blob
    jobs:
      - deployment: jDeploy
        environment: 'Hackaton XP'
        workspace:
          clean: all
        strategy:
          runOnce:
            deploy:
              pool:
                vmImage: 'ubuntu-latest'
              steps:
                - download: current
                - task: AzureFileCopy@4
                  inputs:
                    SourcePath: '$(Pipeline.Workspace)/drop/build'
                    azureSubscription: 'dam.net.br'
                    Destination: 'AzureBlob'
                    storage: 'mercuriofront'
                    ContainerName: '$web'
